name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint_fmt:
    name: cargo fmt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Check formating
        run: cargo fmt -- --check

  lint_clippy:
    name: Clippy
    strategy:
      matrix:
        version: ["1.0", "1.1", "2.0", "2.1", "3.0", "3.1", "3.2", "4.0", "5.0", "6.0"]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Run clippy
        run: |
          ./ci lxc ${{ matrix.version }}
          VERSION=$(echo ${{ matrix.version }} | sed 's/\./_/')
          cargo clippy --features="v${VERSION}" -- --deny warnings

  tests:
    name: Tests
    strategy:
      matrix:
        mode: ["debug", "release"]
        version: ["1.0", "1.1", "2.0", "2.1", "3.0", "3.1", "3.2", "4.0", "5.0", "6.0"]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Run tests (debug)
        if: matrix.mode == 'debug'
        run: |
          ./ci lxc ${{ matrix.version }}
          VERSION=$(echo ${{ matrix.version }} | sed 's/\./_/')
          cargo test --features="v${VERSION}"

      - name: Run tests (release)
        if: matrix.mode == 'release'
        run: |
          ./ci lxc ${{ matrix.version }}
          VERSION=$(echo ${{ matrix.version }} | sed 's/\./_/')
          cargo test --features="v${VERSION}" --release
